#include "/Engine/Private/Common.ush"

RWTexture2D<float4> OutputTexture;
Texture2D<float4>  InputTexture;
SamplerState       InputSampler;

[numthreads(8, 8, 1)]
void MainCS(uint3 DispatchThreadId : SV_DispatchThreadID)
{
    uint2 Pixel = DispatchThreadId.xy;
    float4 color = InputTexture[Pixel];
    float gray = dot(color.rgb, float3(0.299, 0.587, 0.114));
    OutputTexture[Pixel] = float4(gray, gray, gray, color.a);
}